
= Standalone test of XA transactions behaviour of jdbc driver

== Sources

Inspired by example on M$ pages:
http://msdn.microsoft.com/en-us/library/aa342335.aspx

== Compilation:

```
LIBS=""; for I in lib/*; do LIBS=$I:$LIBS; done
rm -rf classes/* && javac -cp $LIBS -d classes src/run/*.java src/util/*.java
```

== Running:

NOTE: be sure to setup the `$LIBS` variable as said before

`java -cp ${LIBS}classes -Dhost=localhost -Ddbtype=postgresql run.test2PC`

=== Possible parameters

Parameters needs to be set *before* the name name of running class.
It means `java -cp classes -Dhost=localhost testXA` works but
`java -cp classes testXA -Dhost=localhost` does not.

 * `-Ddbtype=postgresql`
 * `-Dhost=localhost`
 * `-Dport=1433`
 * `-Ddatabase=crashrec`
 * `-Duser=crashrec`
 * `-Dpassword=crashrec`

To get running debugging

```
java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005 -cp ${LIBS}classes <class.name>
```

== Examples of running some databases

* Oracle: `java -cp ${LIBS}classes -Dhost=localhost -Ddbtype=oracle -Dport=1521 run.test2PC`
* Oracle RAC: `java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005 -cp ${LIBS}classes -Durl=jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=off)(ADDRESS=(PROTOCOL=TCP)(HOST=oracle-12cr1-rac-01.rhev-ci-vms.eng.rdu2.redhat.com)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=dballo))) -Ddbtype=oracle run.test2PC`
